### ISSUE TITLE
pickphotos library showing some error in android studio

### ISSUE THREAD

**Issue by senthil4589** [crosswall/Android-PickPhotos#4]
Error:(12, 26) error: package com.bumptech.glide does not exist

**Comment by mr-cpp** [comment]
i have implemented this library just now
there was not such error
May be do not forgot to write this in project gradle file:
`def supportVersion   = "23.2.1"
def rxVersion        = "1.1.0"
def imageVersion     = "3.7.0"

ext {
    supportV4 = "com.android.support:support-v4:${supportVersion}"
    recyclerview = "com.android.support:recyclerview-v7:${supportVersion}"
    appcompat = "com.android.support:appcompat-v7:${supportVersion}"
    designCompat = "com.android.support:design:${supportVersion}"
    annotations = "com.android.support:support-annotations:${supportVersion}"

    imageloader   = "com.github.bumptech.glide:glide:${imageVersion}"
    rxJava        = "io.reactivex:rxjava:${rxVersion}"
    rxAndroid     = "io.reactivex:rxandroid:${rxVersion}"
}`
